apiVersion: v1
kind: Secret
metadata:
  name: ftgo-secrets
  namespace: default
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: bXlzcWx1c2Vy
  SPRING_DATASOURCE_PASSWORD: bXlzcWxwdw==
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_USER: bXlzcWx1c2Vy
  MYSQL_PASSWORD: bXlzcWxwdw==
